##############################################################################################
#' Phenocam modal

#' @name phenoModal

#' @author
#' James Ross \email{ross.james94@gmail.com} \cr

#' @description  Displays appropriate modal for phenoGET functionality.

#' @param phenoURL Required: URL generated by pheno.GET [string]
#' @param usrDateTime Required: Formatted date and time for bad modal [string]
#' @param isGoodRequest Required: Boolean generated by pheno.GET [boolean]
#' @param siteID Required: SiteID from app [string]

#' @return This function returns nothing

#' @references
#' License: GNU AFFERO GENERAL PUBLIC LICENSE Version 3, 19 November 2007

#' @export phenoModal

# changelog and author contributions / copyrights
#   James M. Ross (2022-07-01)
#     original creation
##############################################################################################
# # Source packages and set options
options(stringsAsFactors = F)

phenoModal <- function(phenoURL,usrDateTime,isGoodRequest,siteID){

  if(isGoodRequest==TRUE){
    showModal(modalDialog(
      title = "Phenocam Image",
      size = "l",
      tags$img(
        src = phenoURL),
      footer = downloadButton("downloadPheno",label = "Download Phenocam Image"),
      easyClose = TRUE))
  }
  else{
    showModal(modalDialog(
      title = "Phenocam Image",
      "No phenocam image available at ",siteID," for Date/Time",usrDateTime,
      size = "s",
      easyClose = TRUE))
  }
}
