
#creator: Nick Harrison
#last updated: 11/15/2018
#Purpose: script to quickly plot two cross-section profiles on top of each other using raw total station data.  
#Note: input .CSV files requires certain formatting criteria (name, mapCode, E, N, H).

#Probably should expand this to compare area and other metrics.    Can also be expanded for more than 2 years of data.   

```{r Set variables for survey data 1}
require(rgdal)
library(rgdal)
library(plotly)

#Queues a directory that contains file paths for each site per survey date.  
siteDirectory1<-read.csv('N:/Science/AQU/Geomorphology_Survey_Data/inputDirectory.csv',head=T,sep=",",stringsAsFactors = F) 

#NEON Domain number (ex: D01).
domainID1<-'D04' 

#Four-digit NEON site code (ex: HOPB).
siteID1<- 'GUIL'  

#The end date of the geomorphology survey (YYYYMMDD).  
surveyDate1<-'20180129' 

#Stipulate 4-digit site code, underscore, and survey year (ex: HOPB_2017). 
surveyID1<- "GUIL_2018"  

#Creates dataframe1 that contains survey data1.  
filePath1 <- siteDirectory1$filePath[which(siteDirectory1$surveyID==surveyID1)]
surveyShapefileName1 <- siteDirectory1$surveyShapefileName[which(siteDirectory1$surveyID==surveyID1)]
surveyPts1 <- readOGR(filePath1,surveyShapefileName1)
surveyPtsDF1 <- as.data.frame(surveyPts1)
```

```{r Set variables for survey data 2}
#NEON Domain number (ex: D01).
domainID2<-'D04' 

#Four-digit NEON site code (ex: HOPB).
siteID2<- 'GUIL'  

#The end date of the geomorphology survey (YYYYMMDD).  
surveyDate2<-'20170825' 

#Stipulate 4-digit site code, underscore, and survey year (ex: HOPB_2017). 
surveyID2<- "GUIL_2017"  

#Creates dataframe1 that contains survey data1.  
filePath2 <- siteDirectory1$filePath[which(siteDirectory1$surveyID==surveyID2)]
surveyShapefileName2 <- siteDirectory1$surveyShapefileName[which(siteDirectory1$surveyID==surveyID2)]
surveyPts2 <- readOGR(filePath2,surveyShapefileName2)
surveyPtsDF2 <- as.data.frame(surveyPts2)
```

```{r If present, creates a dataframe for all discharge XS1 points, transforms N/Es to horizontal distances, plots XS profile, and calculates bankfull width.}

#Creates dataframe of all points associated with transect DSC1.  
dischargePointsXS1=subset(surveyPtsDF1,mapCode=="Transect_DSC1_Original")
dischargePointsXS1<-dischargePointsXS1[
  with(dischargePointsXS1,order(dischargePointsXS1$E)),
  ]
rownames(dischargePointsXS1)<-seq(length=nrow(dischargePointsXS1)) 
dischargePointsXS1$surveyYear<-surveyDate1

#To manually select NorthStart and EastStart coordinates
dischargeXS1NorthStart<-dischargePointsXS1$N[49]
dischargeXS1EastStart<-dischargePointsXS1$E[49]

#Assigns a raw Distance value to each point relative to the NorthStart and EastStart coordinates.
for(i in 1:(length(dischargePointsXS1$name))){
      dischargeXS1PointN<-dischargePointsXS1$N[i]
      dischargeXS1PointE<-dischargePointsXS1$E[i]
      dischargePointsXS1$DistanceRaw[i]<-sqrt(((dischargeXS1PointN-dischargeXS1NorthStart)^2)+((dischargeXS1PointE-dischargeXS1EastStart)^2))
}


#To manually select ReferenceDistance:
dischargeXS1ReferenceDistance<-dischargePointsXS1$DistanceRaw[49]

#Sets Horizontal adjustment value based on reference point coordinate.  
dischargeXS1HorizontalAdjust<-0-dischargeXS1ReferenceDistance

#Transforms raw distance to adjusted distance based on reference distance point.
for(i in 1:(length(dischargePointsXS1$name))){
      dischargePointsXS1$DistanceAdj[i]<-dischargePointsXS1$DistanceRaw[i]+dischargeXS1HorizontalAdjust
  }

#Sets plot1 settings.  
xAxisTitle1<-list(title="Elevation (m)",zeroline=FALSE)
yAxisTitle1<-list(title="Distance  (m)",zeroline=FALSE)
font<-list(size=12,color='black')

#Plot XS1.
plot_ly(data=dischargePointsXS1,x=~DistanceAdj, y=~H, name='Distance vs. Elevation', type='scatter', mode='lines+markers', text=~name)%>%
  layout(title = siteID1, xaxis=xAxisTitle1, yaxis=yAxisTitle1)
```

```{r If present, creates a dataframe for all discharge XS2 points, transforms N/Es to horizontal distances, plots XS profile, and calculates bankfull width.}

#Creates dataframe of all points associated with transect DSC2.  
dischargePointsXS2=subset(surveyPtsDF2,mapCode=="Transect_DSC1")
dischargePointsXS2<-dischargePointsXS2[
  with(dischargePointsXS2,order(dischargePointsXS2$E)),
  ]
rownames(dischargePointsXS2)<-seq(length=nrow(dischargePointsXS2)) 
dischargePointsXS2$surveyYear<-surveyDate2


#To manually select NorthStart and EastStart coordinates
dischargeXS2NorthStart<-dischargePointsXS2$N[30]
dischargeXS2EastStart<-dischargePointsXS2$E[30]

#Assigns a raw Distance value to each point relative to the NorthStart and EastStart coordinates.
for(i in 1:(length(dischargePointsXS2$name))){
      dischargeXS2PointN<-dischargePointsXS2$N[i]
      dischargeXS2PointE<-dischargePointsXS2$E[i]
      dischargePointsXS2$DistanceRaw[i]<-sqrt(((dischargeXS2PointN-dischargeXS2NorthStart)^2)+((dischargeXS2PointE-dischargeXS2EastStart)^2))
}

#To manually select ReferenceDistance:
dischargeXS2ReferenceDistance<-dischargePointsXS2$DistanceRaw[29]

#Sets Horizontal adjustment value based on reference point coordinate.  
dischargeXS2HorizontalAdjust<-0-dischargeXS2ReferenceDistance

#Transforms raw distance to adjusted distance based on reference distance point.
for(i in 1:(length(dischargePointsXS2$name))){
      dischargePointsXS2$DistanceAdj[i]<-dischargePointsXS2$DistanceRaw[i]+dischargeXS2HorizontalAdjust
  }

#Plot XS2.
plot_ly(data=dischargePointsXS2,x=~DistanceAdj, y=~H, name='Distance vs. Elevation', type='scatter', mode='lines+markers', text=~name)%>%
  layout(title = siteID2, xaxis=xAxisTitle1, yaxis=yAxisTitle1)
```

```{r plot both cross-sections}

plot_ly(data=dischargePointsXS1,x=~DistanceAdj, y=~H, name=surveyDate1, type='scatter', mode='lines+markers', text=~name)%>%
  add_trace(data=dischargePointsXS2, x=~DistanceAdj, y=~H, name=surveyDate2, type='scatter',mode='lines+markers',text=~name)%>%
  layout(title = siteID1, xaxis=xAxisTitle1, yaxis=yAxisTitle1)
```
